project_name: 'ccfb'

#train_path: '/home/work/yangfg/corpus/face/CCFB/train-data'
#train_path: '/home/work/yangfg/corpus/face/CCFB/all-train/Caucasian'
train_path: '/home/work/yangfg/corpus/face/CCFB/all-train/Asian'
#train_path: '/home/work/yangfg/experiment/face-recognition/ccfb/train_data/new_training/train'
grad_clip: 5.
num_classes: 16520

faces_dir: '/home/work/yangfg/corpus/face/CCFB/all-train/Asian'
is_aver: False
db_dir: './db'
