project_name: 'false-name'

train_path: '/home/work/yangfg/corpus/driver/2.labeled-xml/mix-face/false-name-train'
grad_clip: 5.
num_classes: 16520

faces_dir: '/home/work/yangfg/corpus/driver/2.labeled-xml/mix-face/false-name-val'
is_aver: False
db_dir: './db'
